### ISSUE TITLE
No fall feather

### ISSUE THREAD

**Issue by jogavin** [RoyalRaid/VenomPvP#34]
https://gyazo.com/a64d47392851c430be42b6d665d0b062

it kinda became a golden apple as its description. Can't really fix now :/

**Comment by RoyalRaid** [comment]
Need more info, where abouts is this located?

**Comment by jogavin** [comment]
All no fall items have this description as I can see

**Comment by Zaid-Ali** [comment]
This issue is the lore of the VenomPerk: No Feather Fall -

As seen in this link: [http://prntscr.com/dtwu1s](url) .... the wrong lore has been put on it (the lore for the Extra Health Apple.



The correct lore should be: 

"Place this anywhere in your inventory to receive no fall damage where ever you go!"

PIC (from /token shop): [http://prntscr.com/dtwuy1](url)

**Comment by RoyalRaid** [comment]
Issues has been fixed, Dev made a mistake in his code ;p
~ Resolved
