### ISSUE TITLE
[/f warp (name)] IN COMBAT WORKS - Takes you out of combat as well as tping you.

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#43]
Currently cannot /f warp in combat but if you /f warp (name) you will be tped.

Needs fixing ASAP.

WATCH THE VIDEO: [https://youtu.be/meKgh4I51AE](url)

**Comment by Zaid-Ali** [comment]
#41

**Comment by RoyalRaid** [comment]
Since the source code is freely available im going to get my dev to make changes to the plugin. Just a feature so i can disable all commands and not have to write each command i want to disable. Will make life so much easier
Will let you know once its done.

ps. im unable to patch the glitch with what i have so far which is why im getting the dev to make this patch

**Comment by RoyalRaid** [comment]
Okay, so dev kinda fucked me around on this one. Got my other dev to do it since it was a smaller project. So he has coded a addon to our CombatTag plugin which allows us to instead whitelist commands instead of blacklist them, any commands not whitelisted will be blocked. Currently only /ct is enabled, if there are any others let me know.

Ps. Changes wont be applied till a server restart

~Setting to resolved

**Comment by Zaid-Ali** [comment]
Posted in #50
