### ISSUE TITLE
[/wild] WORKS IN COMBAT.

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#46]
/wild also works in combat. #

**Comment by Zaid-Ali** [comment]
#43

**Comment by RoyalRaid** [comment]
Okay, so dev kinda fucked me around on this one. Got my other dev to do it since it was a smaller project. So he has coded a addon to our CombatTag plugin which allows us to instead whitelist commands instead of blacklist them, any commands not whitelisted will be blocked. Currently only /ct is enabled, if there are any others let me know.

Ps. Changes wont be applied till a server restart

~Setting to resolved

**Comment by Zaid-Ali** [comment]
Posted in #50
