### ISSUE TITLE
[/duel;/duel accept] WORKS IN COMBAT!

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#50]
**/duel** AND **/duel accept** NEED DISABLING IN COMBAT

**Comment by Zaid-Ali** [comment]
#43 #46

**Comment by RoyalRaid** [comment]
Will be patched today, i had it done just there was a compatibility issue with our bukkit jar.

**Comment by RoyalRaid** [comment]
Okay, so dev kinda fucked me around on this one. Got my other dev to do it since it was a smaller project. So he has coded a addon to our CombatTag plugin which allows us to instead whitelist commands instead of blacklist them, any commands not whitelisted will be blocked. Currently only /ct is enabled, if there are any others let me know.

Ps. Changes wont be applied till a server restart

~Setting to resolved

**Comment by Zaid-Ali** [comment]
You want to add:

- factions.chat
- essentials.tpa
- essentials.tptoggle
- essentials.msg
- featherboard.toggle
- venom.armor.toggle
- venom.gapplecooldown
- venom.global
- venom.list
- venom.ping

**Comment by RoyalRaid** [comment]
Recieved fix today, Every command is now disabled besides:
  - ct
  - ctlog
  - logout
  - ctlogout
  - ctpluslogout
  - f chat p
  - f chat f
  - f chat a
  - f c p
  - f c a
  - f c f
  - faction chat p
  - faction chat f
  - faction chat a
  - faction c p
  - faction c f
  - faction c a
  - f c public
  - f c ally
  - f c faction
  - faction chat public
  - faction chat ally
  - faction chat faction
  - tptoggle
  - msg
  - fb toggle
  - featherboard toggle
  - list
  - staff
  - ping
  - toggle armour
  - m
  - w
  - whisper

If you want me to add anymore, let me know
