### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#84]
### Venoms' playerbase is at an all time low. 
**What would be the point of getting an AD in February when all you will get is a high playerbase of temporary players; explorer ranks that join play for an hour or so then never come back?**

I'm pretty sure if you want a successful community you want "loyal" players who come back to Venom after joining. 

First impressions when they join the server (current reset); the map is worn, the top factions have already been defined and there is no raiding them and the majority of people are geared to the max meaning these explorers that join stand NO CHANCE. This would cause them to leave, most likely to a server with a more recent reset. 

You would be spending money to maintain Venom until the AD runs out, and then we will be in the same position as current day; where Venoms' playerbase is at an all time low in months and still declining. 

Skyblock is fucked beyond belief, the eco needs fixing for next reset as right now it is unbelievably op.

### You could Reset in time for the AD in Febuary: 

Our resets are hype. Resets bring back old players of Venom as well as new.
New Map, New Spawn, New Feel.

All the fixes we have done this reset will make the next reset better mainly AutoRestarts, meaning a reduction is lag spikes and tps drops. 

You are going to see the AD go to waste if there is no reset and an actual incentive for the majority of new players to stay on venom (which will bring back old players until the playerbase falls again).

### What we need:

- New Spawn from your builder
- Test Server - There is plenty of time to test everything, including new plugin suggestions (i.e. updated /duel plugin)
- You

**Comment by RoyalRaid** [comment]
Yeah we had a discussion about this where i said i would like to reset in February instead of waiting till March, The issue back then was factions were still growing and stuff. But come to re-think it im going to be putting 5k~ into a ad that might backfire due to our current situation. 

One issue i already see is ad starts on a Wednesday (1st of Feb) would we reset on that wednesday or wait till weekend?

Another issue being, We have a spawn but jack is gonna have to work flat out to get a warzone/koth areas done.

For skyblock we might have to just do eco fixes, reset everything but might not have a new spawn, that being the issue right now unless i can find someone to build one in such little time.

Guess all these things need to be taken into consideration, but a reset is most definite!

**Comment by Zaid-Ali** [comment]
Most likely wait till weekend to open - More players have free time etc.

Jack will get it done, we have 13 days till reset date. Plenty of time to get it done and test everything beforehand.

I'm honestly fine with just an economy overhaul for skyblock because that is really the main problem with skyblock right now alongside vote party key farming.

**Comment by Zaid-Ali** [comment]
Most likely wait till weekend to open - More players have free time etc.

Jack will get it done, we have 13 days till reset date. Plenty of time to get it done and test everything beforehand.

I'm honestly fine with just an economy overhaul for skyblock because that is really the main problem with skyblock right now alongside vote party key farming.

**Comment by Kauldwin** [comment]
13 DAYS??! I cant make a full warzone with NO IDEA what you want, nor a spawn. I need a spawn first. A good one at that. Matt PM me full info on what you want i need this ASAP if your giving me 14 days.

**Comment by RoyalRaid** [comment]
Tried to PM you jack, You aint replying to pm. I might try and split a ad with someone instead which will give us an extra 2 weeks

**Comment by Blackouma** [comment]
Possibly get a spawn the same size of the current one? So we can use the same warzone. Don't think it'd hurt too much.
